kind: Service
apiVersion: v1
metadata:
  name: rancher-pipeline-test1
spec:
  selector:
    app: rancher-pipeline-test1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-pipeline-test1
  labels:
    app: greenhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-pipeline-test1
  template:
    metadata:
      labels:
        app: rancher-pipeline-test1
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080